from app.domain.agent.prompts.industrial import INDUSTRIAL_SYSTEM_PROMPT, AGENTS_MD_CONTENT, TEMPORAL_ROUTER_PROMPT

__all__ = ["INDUSTRIAL_SYSTEM_PROMPT", "AGENTS_MD_CONTENT", "TEMPORAL_ROUTER_PROMPT"]
